### ISSUE TITLE
Enable proxy

### ISSUE THREAD

**Issue by sigurdne** [Infamoustrey/smartsheet#8]
How about enabelling proxy - like so?
` 
   /**
     * Configure API Client
     *
     * config
     *     token => A valid smartsheet API Token
     *
     * @param array $config
     */
    public function __construct(array $config)
    {
        $this->token = $config['token'];

        $authHeader = "Bearer " . $this->token;

        $this->guzzleClient = new GuzzleClient([
            'base_uri' => self::BASE_URL,
            'headers' => [
                'Authorization' => $authHeader
            ],
            'proxy' => !empty($config['proxy']) ? $config['proxy'] : null
        ]);
  }
`

**Comment by Infamoustrey** [comment]
added
