### ISSUE TITLE
Enable links

### ISSUE THREAD

**Issue by sigurdne** [Infamoustrey/smartsheet#9]
It seems like that in order to insert a hyperlink - one needs to alter the generateRowCells()

Example:
`
	$rows					 = array();
	$rows['Primary Column']	 = 'test1';
	$rows['Column2']		 = 'test2';
	$rows['Column3']		 = array(
		'value'		 => 'eksempel på link',
		'hyperlink'	 => 'https://community.smartsheet.com/discussion/20286/hyperlink-api'
	);

	$sheet->addRow($rows);
`

Add a new check for hyperlinks within the check for array (sorry for the formatting):

` 
else if (key_exists('hyperlink', $value)) {
  $newCells[] = [
    'columnId'	 => $this->getColumnId($title),
    'value'		 => $value['value'],
    'hyperlink'	 => $value['hyperlink']
  ];
}`

**Comment by Infamoustrey** [comment]
added
